# -*- coding: utf-8 -*-
"""18Feb Assessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19uXG_Nbla6HnmvZGgj1Qm-_ungJD-vBt
"""

# API - application programming interface, Ex. for any application to give you the data, ex. Google search for any data, the client (google) goes to server and gives u the data

#2. Advantages of API-Effienciency , Automation, Intergration Disadvantages: Security Issues, Complexity, Compatibility Issues

#3. web API- Uses HTTP, WEb API is a subset of API

#4. REST AND SOAP ARCHITECTURE

#REST- REPRESENTATIONAL STATE TRANSFER- HTTP Hypertextransferprotocol- PUt GET POST DeLETe, Known for simplicity, scalability and flexibility
#SIMPLE OBJeCT TRANSFER PROTOCOL-TCP/SMPT - XML-> WSDL- Web seervice description Language ->Wrtie a rule and implement it

